### ISSUE TITLE
pspy requiring ducc but not installing it as a dependency

### ISSUE THREAD

**Issue by sgiardie** [simonsobs/pspy#72]
pspy requires ducc [here](https://github.com/simonsobs/pspy/blob/6602a006ea2ef66f396252f45572e7090c639973/pspy/fft.py#L36), but it does not require its installation

**Comment by xgarrido** [comment]
We didn't want to add `ducc` as a `pspy` dependency since the fft computation is a temporary fix until `pixell` properly integrates `ducc`. This is now the case in 0.19 version release of `pixell` (fft support as well as alm computation). We didn't have time to check `pspy` against `pixell` 0.19 but it should be pretty straightforward. So, if you want to use this https://github.com/simonsobs/pspy/blob/master/pspy/fft.py#L35 then you have to install `ducc` by yourself `pip install ducc0`
